import type {
  Course,
  CurrentUser,
  Reservation,
  TeacherProfile,
} from './types'

/** Avatares y portadas mock (servicios públicos estables). */
const avatar = (n: number) => `https://i.pravatar.cc/400?img=${n}`
const cover = (seed: string) =>
  `https://picsum.photos/seed/teduca-${seed}/800/500`

export const mockCurrentUser: CurrentUser = {
  id: 'me',
  name: 'Estudiante TEDUCA',
  email: 'estudiante@teduca.dev',
  avatar: avatar(12),
  role: 'student',
}

export const mockTeachers: TeacherProfile[] = [
  {
    id: 't1',
    userId: 'u1',
    name: 'Valentina Ríos',
    avatar: avatar(5),
    specialty: 'Matemática · Cálculo y Álgebra',
    bio: 'Apasionada por hacer que las matemáticas se sientan simples e intuitivas. Enseño con ejemplos del mundo real y mucha práctica guiada.',
    experienceYears: 8,
    university: 'Universidad de Buenos Aires',
    courseIds: ['c1', 'c2'],
    modality: 'both',
    hourlyPrice: 25,
    currency: 'USD',
    languages: ['Español', 'Inglés'],
    availability: [
      { day: 'Lun', slots: ['09:00 - 12:00', '18:00 - 21:00'] },
      { day: 'Mié', slots: ['15:00 - 19:00'] },
      { day: 'Vie', slots: ['09:00 - 13:00'] },
    ],
    rating: 4.9,
    reviewsCount: 214,
    studentsCount: 1280,
    categories: ['Matemática', 'Ciencias'],
    location: 'Buenos Aires, AR',
    socials: [
      { type: 'linkedin', url: 'https://linkedin.com' },
      { type: 'website', url: 'https://teduca.dev' },
    ],
  },
  {
    id: 't2',
    userId: 'u2',
    name: 'Mateo Fernández',
    avatar: avatar(13),
    specialty: 'Programación · Full-Stack Web',
    bio: 'Ingeniero de software y mentor. Te acompaño desde tu primer "Hello World" hasta desplegar tu propia app en producción.',
    experienceYears: 10,
    university: 'Universidad Politécnica de Madrid',
    courseIds: ['c3', 'c4'],
    modality: 'virtual',
    hourlyPrice: 40,
    currency: 'USD',
    languages: ['Español', 'Inglés', 'Portugués'],
    availability: [
      { day: 'Mar', slots: ['10:00 - 14:00'] },
      { day: 'Jue', slots: ['16:00 - 20:00'] },
      { day: 'Sáb', slots: ['09:00 - 12:00'] },
    ],
    rating: 4.8,
    reviewsCount: 341,
    studentsCount: 2140,
    categories: ['Programación', 'Tecnología'],
    location: 'Remoto',
    socials: [
      { type: 'website', url: 'https://teduca.dev' },
      { type: 'twitter', url: 'https://twitter.com' },
    ],
  },
  {
    id: 't3',
    userId: 'u3',
    name: 'Camila Torres',
    avatar: avatar(20),
    specialty: 'Inglés · Business & Conversation',
    bio: 'Certificada CELTA. Clases dinámicas centradas en que hables desde el día uno, con foco en fluidez y confianza.',
    experienceYears: 6,
    university: 'University of Cambridge',
    courseIds: ['c5'],
    modality: 'virtual',
    hourlyPrice: 22,
    currency: 'USD',
    languages: ['Inglés', 'Español'],
    availability: [
      { day: 'Lun', slots: ['08:00 - 11:00'] },
      { day: 'Mié', slots: ['18:00 - 22:00'] },
      { day: 'Vie', slots: ['14:00 - 18:00'] },
    ],
    rating: 4.95,
    reviewsCount: 189,
    studentsCount: 980,
    categories: ['Idiomas'],
    location: 'Córdoba, AR',
    socials: [{ type: 'instagram', url: 'https://instagram.com' }],
  },
  {
    id: 't4',
    userId: 'u4',
    name: 'Diego Salazar',
    avatar: avatar(33),
    specialty: 'Física · Mecánica y Electromagnetismo',
    bio: 'Doctor en Física. Convierto conceptos abstractos en algo que podés ver y tocar. Ideal para universitarios y preparación de exámenes.',
    experienceYears: 12,
    university: 'Universidad de Chile',
    courseIds: ['c6'],
    modality: 'both',
    hourlyPrice: 30,
    currency: 'USD',
    languages: ['Español'],
    availability: [
      { day: 'Mar', slots: ['09:00 - 12:00'] },
      { day: 'Jue', slots: ['15:00 - 18:00'] },
    ],
    rating: 4.7,
    reviewsCount: 156,
    studentsCount: 640,
    categories: ['Física', 'Ciencias'],
    location: 'Santiago, CL',
  },
  {
    id: 't5',
    userId: 'u5',
    name: 'Sofía Méndez',
    avatar: avatar(45),
    specialty: 'Diseño UX/UI · Product Design',
    bio: 'Product Designer en tech. Te enseño a pensar en el usuario, prototipar en Figma y armar un portfolio que consiga entrevistas.',
    experienceYears: 7,
    university: 'Universidad de Palermo',
    courseIds: ['c7'],
    modality: 'virtual',
    hourlyPrice: 35,
    currency: 'USD',
    languages: ['Español', 'Inglés'],
    availability: [
      { day: 'Lun', slots: ['16:00 - 20:00'] },
      { day: 'Sáb', slots: ['10:00 - 14:00'] },
    ],
    rating: 4.85,
    reviewsCount: 203,
    studentsCount: 1120,
    categories: ['Diseño', 'Tecnología'],
    location: 'Buenos Aires, AR',
    socials: [{ type: 'linkedin', url: 'https://linkedin.com' }],
  },
  {
    id: 't6',
    userId: 'u6',
    name: 'Lucas Moreno',
    avatar: avatar(51),
    specialty: 'Química · Orgánica e Inorgánica',
    bio: 'Profe de química con paciencia infinita. Explico paso a paso hasta que el "click" llega. Preparación de ingresos y secundaria.',
    experienceYears: 9,
    university: 'Universidad Nacional de La Plata',
    courseIds: ['c8'],
    modality: 'in-person',
    hourlyPrice: 20,
    currency: 'USD',
    languages: ['Español'],
    availability: [
      { day: 'Mié', slots: ['09:00 - 13:00'] },
      { day: 'Vie', slots: ['15:00 - 19:00'] },
    ],
    rating: 4.6,
    reviewsCount: 98,
    studentsCount: 410,
    categories: ['Química', 'Ciencias'],
    location: 'La Plata, AR',
  },
  {
    id: 't7',
    userId: 'u7',
    name: 'Antonella Bruno',
    avatar: avatar(24),
    specialty: 'Data Science · Python & ML',
    bio: 'Data Scientist. De pandas a modelos de machine learning con proyectos reales. Ideal si querés dar el salto a datos.',
    experienceYears: 6,
    university: 'Universidad Torcuato Di Tella',
    courseIds: ['c9'],
    modality: 'virtual',
    hourlyPrice: 45,
    currency: 'USD',
    languages: ['Español', 'Inglés'],
    availability: [
      { day: 'Mar', slots: ['18:00 - 21:00'] },
      { day: 'Jue', slots: ['18:00 - 21:00'] },
    ],
    rating: 4.9,
    reviewsCount: 167,
    studentsCount: 890,
    categories: ['Programación', 'Datos'],
    location: 'Remoto',
    socials: [{ type: 'linkedin', url: 'https://linkedin.com' }],
  },
  {
    id: 't8',
    userId: 'u8',
    name: 'Javier Ocampo',
    avatar: avatar(60),
    specialty: 'Historia · Contemporánea y del Arte',
    bio: 'Historiador y narrador. Convierto fechas y nombres en relatos que se recuerdan. Secundaria, universidad y curiosos.',
    experienceYears: 11,
    university: 'Universidad de Salamanca',
    courseIds: ['c10'],
    modality: 'both',
    hourlyPrice: 18,
    currency: 'USD',
    languages: ['Español', 'Inglés', 'Italiano'],
    availability: [
      { day: 'Lun', slots: ['14:00 - 18:00'] },
      { day: 'Mié', slots: ['14:00 - 18:00'] },
    ],
    rating: 4.75,
    reviewsCount: 122,
    studentsCount: 530,
    categories: ['Historia', 'Humanidades'],
    location: 'Salamanca, ES',
  },
]

export const mockCourses: Course[] = [
  { id: 'c1', title: 'Cálculo I desde cero', image: cover('calculo'), category: 'Matemática', description: 'Límites, derivadas e integrales con enfoque práctico y visual.', level: 'beginner', durationHours: 24, teacherId: 't1', teacherName: 'Valentina Ríos', price: 89, currency: 'USD', rating: 4.9, reviewsCount: 132 },
  { id: 'c2', title: 'Álgebra Lineal Aplicada', image: cover('algebra'), category: 'Matemática', description: 'Vectores, matrices y transformaciones para ciencia de datos e ingeniería.', level: 'intermediate', durationHours: 20, teacherId: 't1', teacherName: 'Valentina Ríos', price: 99, currency: 'USD', rating: 4.8, reviewsCount: 74 },
  { id: 'c3', title: 'Full-Stack Web con React & Node', image: cover('fullstack'), category: 'Programación', description: 'Construí y desplegá una app completa: frontend, API y base de datos.', level: 'intermediate', durationHours: 48, teacherId: 't2', teacherName: 'Mateo Fernández', price: 199, currency: 'USD', rating: 4.9, reviewsCount: 256 },
  { id: 'c4', title: 'TypeScript Profesional', image: cover('typescript'), category: 'Programación', description: 'Tipado avanzado, patrones y arquitectura para proyectos escalables.', level: 'advanced', durationHours: 16, teacherId: 't2', teacherName: 'Mateo Fernández', price: 129, currency: 'USD', rating: 4.85, reviewsCount: 98 },
  { id: 'c5', title: 'Inglés para Negocios', image: cover('english'), category: 'Idiomas', description: 'Reuniones, emails y presentaciones con confianza. Nivel B1 a C1.', level: 'intermediate', durationHours: 30, teacherId: 't3', teacherName: 'Camila Torres', price: 149, currency: 'USD', rating: 4.95, reviewsCount: 187 },
  { id: 'c6', title: 'Física Universitaria', image: cover('fisica'), category: 'Física', description: 'Mecánica y electromagnetismo con resolución guiada de problemas.', level: 'advanced', durationHours: 36, teacherId: 't4', teacherName: 'Diego Salazar', price: 159, currency: 'USD', rating: 4.7, reviewsCount: 89 },
  { id: 'c7', title: 'Diseño UX/UI de Producto', image: cover('uxui'), category: 'Diseño', description: 'De la investigación al prototipo en Figma. Armá un portfolio real.', level: 'beginner', durationHours: 28, teacherId: 't5', teacherName: 'Sofía Méndez', price: 179, currency: 'USD', rating: 4.9, reviewsCount: 143 },
  { id: 'c8', title: 'Química Orgánica', image: cover('quimica'), category: 'Química', description: 'Grupos funcionales, reacciones y mecanismos explicados con claridad.', level: 'intermediate', durationHours: 22, teacherId: 't6', teacherName: 'Lucas Moreno', price: 79, currency: 'USD', rating: 4.6, reviewsCount: 61 },
  { id: 'c9', title: 'Data Science con Python', image: cover('data'), category: 'Datos', description: 'Pandas, visualización y tu primer modelo de machine learning.', level: 'intermediate', durationHours: 40, teacherId: 't7', teacherName: 'Antonella Bruno', price: 219, currency: 'USD', rating: 4.9, reviewsCount: 174 },
  { id: 'c10', title: 'Historia del Arte', image: cover('arte'), category: 'Historia', description: 'Del Renacimiento al arte contemporáneo en relatos memorables.', level: 'beginner', durationHours: 18, teacherId: 't8', teacherName: 'Javier Ocampo', price: 69, currency: 'USD', rating: 4.8, reviewsCount: 52 },
]

export const mockReservations: Reservation[] = [
  {
    id: 'r1',
    teacherId: 't2',
    teacherName: 'Mateo Fernández',
    teacherAvatar: avatar(13),
    courseId: 'c3',
    courseTitle: 'Full-Stack Web con React & Node',
    date: '2026-08-05',
    time: '18:00',
    modality: 'virtual',
    price: 40,
    currency: 'USD',
    status: 'confirmed',
    createdAt: '2026-07-30T10:00:00Z',
  },
  {
    id: 'r2',
    teacherId: 't3',
    teacherName: 'Camila Torres',
    teacherAvatar: avatar(20),
    courseId: 'c5',
    courseTitle: 'Inglés para Negocios',
    date: '2026-08-08',
    time: '19:00',
    modality: 'virtual',
    price: 22,
    currency: 'USD',
    status: 'pending',
    createdAt: '2026-07-31T09:00:00Z',
  },
]
