"""add merch_products and announcements tables

Revision ID: 03842e402b53
Revises: f3a2e401004e
Create Date: 2026-08-07 18:16:07.621406

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '03842e402b53'
down_revision: str | None = 'f3a2e401004e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('info', 'event', 'alert', name='announcement_type'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merch_products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_file_assets_access_level'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_bucket'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_bucket_path'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_category'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_course_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_file_type'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_lesson_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_status'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_uploader_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.alter_column('marketplace_courses', 'image',
               existing_type=sa.VARCHAR(length=512),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'category',
               existing_type=sa.VARCHAR(length=60),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'duration_hours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reservations', 'modality',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reservations', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reservations', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('swipes', 'matched',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'specialty',
               existing_type=sa.VARCHAR(length=160),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'bio',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'university',
               existing_type=sa.VARCHAR(length=160),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'modality',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'hourly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'location',
               existing_type=sa.VARCHAR(length=160),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'students_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('teacher_profiles_user_id_key'), 'teacher_profiles', type_='unique')
    op.alter_column('user_onboarding', 'is_edu_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'goals',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'subject_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'project_interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'learning_styles',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'current_step',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_onboarding', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('user_onboarding_user_id_key'), 'user_onboarding', type_='unique')
    op.drop_constraint(op.f('user_onboarding_username_key'), 'user_onboarding', type_='unique')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_onboarding_username'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_username'), 'user_onboarding', ['username'], unique=True)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_onboarding_username'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_username'), 'user_onboarding', ['username'], unique=False)
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_onboarding_username_key'), 'user_onboarding', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_onboarding_user_id_key'), 'user_onboarding', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_onboarding', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'current_step',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'learning_styles',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'project_interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'subject_tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'goals',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=False)
    op.alter_column('user_onboarding', 'is_edu_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('teacher_profiles_user_id_key'), 'teacher_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('teacher_profiles', 'students_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'location',
               existing_type=sa.VARCHAR(length=160),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'hourly_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'modality',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'virtual'::character varying"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'university',
               existing_type=sa.VARCHAR(length=160),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'bio',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('teacher_profiles', 'specialty',
               existing_type=sa.VARCHAR(length=160),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('swipes', 'matched',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('reservations', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('reservations', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('reservations', 'modality',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'virtual'::character varying"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'currency',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'USD'::character varying"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'duration_hours',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'beginner'::character varying"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'category',
               existing_type=sa.VARCHAR(length=60),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=False)
    op.alter_column('marketplace_courses', 'image',
               existing_type=sa.VARCHAR(length=512),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.create_table('file_assets',
    sa.Column('uploader_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('lesson_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bucket', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('file_assets_course_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('file_assets_lesson_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('file_assets_uploader_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_assets_pkey'))
    )
    op.create_index(op.f('ix_file_assets_uploader_id'), 'file_assets', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_file_assets_status'), 'file_assets', ['status'], unique=False)
    op.create_index(op.f('ix_file_assets_lesson_id'), 'file_assets', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_file_assets_file_type'), 'file_assets', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_assets_course_id'), 'file_assets', ['course_id'], unique=False)
    op.create_index(op.f('ix_file_assets_category'), 'file_assets', ['category'], unique=False)
    op.create_index(op.f('ix_file_assets_bucket_path'), 'file_assets', ['bucket', 'storage_path'], unique=True)
    op.create_index(op.f('ix_file_assets_bucket'), 'file_assets', ['bucket'], unique=False)
    op.create_index(op.f('ix_file_assets_access_level'), 'file_assets', ['access_level'], unique=False)
    op.drop_table('merch_products')
    op.drop_table('announcements')
    # ### end Alembic commands ###
