"""add course reviews

Revision ID: 35e6e0bb0b3c
Revises: 03842e402b53
Create Date: 2026-08-07 19:42:17.874004

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '35e6e0bb0b3c'
down_revision: str | None = '03842e402b53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_reviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['marketplace_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_course_review')
    )
    op.create_index(op.f('ix_course_reviews_course_id'), 'course_reviews', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_reviews_user_id'), 'course_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_reviews_user_id'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_course_id'), table_name='course_reviews')
    op.drop_table('course_reviews')
    # ### end Alembic commands ###
