"""analytics events ml

Revision ID: f4fdabf5be04
Revises: 3bbfd4ffbeec
Create Date: 2026-07-24 13:38:18.769154

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f4fdabf5be04'
down_revision: str | None = '3bbfd4ffbeec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('ml_recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_recommendations_created_at'), 'ml_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_recommendations_kind'), 'ml_recommendations', ['kind'], unique=False)
    op.create_index(op.f('ix_ml_recommendations_user_id'), 'ml_recommendations', ['user_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_created_at'), 'user_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_created_at'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_ml_recommendations_user_id'), table_name='ml_recommendations')
    op.drop_index(op.f('ix_ml_recommendations_kind'), table_name='ml_recommendations')
    op.drop_index(op.f('ix_ml_recommendations_created_at'), table_name='ml_recommendations')
    op.drop_table('ml_recommendations')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
