import type { Achievement } from './types'

/** Catálogo de logros de TEDUCA. El desbloqueo real llegará del backend. */
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'primer-curso',
    title: 'Primer Paso',
    description: 'Completá tu primer curso.',
    icon: 'graduation',
    unlockedAt: null,
    xpReward: 50,
    category: 'milestone',
  },
  {
    id: 'primera-mentoria',
    title: 'Primera Mentoría',
    description: 'Asistí a tu primera mentoría.',
    icon: 'sparkles',
    unlockedAt: null,
    xpReward: 40,
    category: 'learning',
  },
  {
    id: 'cien-puntos',
    title: 'Centurión',
    description: 'Alcanzá 100 XP.',
    icon: 'star',
    unlockedAt: null,
    xpReward: 30,
    category: 'milestone',
  },
  {
    id: 'siete-dias',
    title: 'Constancia',
    description: 'Mantené 7 días de racha.',
    icon: 'flame',
    unlockedAt: null,
    xpReward: 70,
    category: 'streak',
  },
  {
    id: 'primer-proyecto',
    title: 'Builder',
    description: 'Creá tu primer proyecto.',
    icon: 'hammer',
    unlockedAt: null,
    xpReward: 60,
    category: 'milestone',
  },
  {
    id: 'top-10',
    title: 'Top 10',
    description: 'Entrá al top 10 de participación.',
    icon: 'trophy',
    unlockedAt: null,
    xpReward: 100,
    category: 'social',
  },
  {
    id: 'estudiante-destacado',
    title: 'Destacado',
    description: 'Reconocido como estudiante destacado.',
    icon: 'award',
    unlockedAt: null,
    xpReward: 90,
    category: 'social',
  },
  {
    id: 'match-maestro',
    title: 'Match Maestro',
    description: 'Realizá 5 matches con profesores.',
    icon: 'users',
    unlockedAt: null,
    xpReward: 50,
    category: 'social',
  },
]
